### ISSUE TITLE
Add option to use WebGui settings

### ISSUE THREAD

**Issue by kachook** [innightwolfsleep/text-generation-webui-telegram_bot#11]
Wondering if it is posible to have an option for a bot to follow generation parameters that are selected within WebGui instead of configuring them separatelly for a bot and WebGui.

Thanks.

**Comment by innightwolfsleep** [comment]
I going to make parameter file selector for individual users, something like chars selector.

**Comment by innightwolfsleep** [comment]
Added preset load button. Influence on all conversations with bot.

**Comment by innightwolfsleep** [comment]
Added preset load button
