### ISSUE TITLE
generation error: character_menu

### ISSUE THREAD

**Issue by thecookingsenpai** [innightwolfsleep/text-generation-webui-telegram_bot#110]
As per title, when I try to talk with the bot on telegram i have the following:

Output generatd in 5.02 seconds
generation error: 'character_menu'
<GENERATION FAIL>

And then the telegram bot send an empty message

EDIT: The issue is present when Silero TTS Extension is activated and generates audio. Would be nice to have support for the TTS generation so that the bot could send vocals

**Comment by innightwolfsleep** [comment]
Repeat this bug, but currently can't find a root of problem. Perhaps, this can't be solved without changes in text-generator-webui. Seems, this bug happend even in api mode.

P.s. Silero TTS voice generator already integrated in telegram_bot. You dont need run silero_tts extension to get tts within telegram_bot.

**Comment by thecookingsenpai** [comment]
> P.s. Silero TTS voice generator already integrated in telegram_bot. You dont need run silero_tts extension to get tts within telegram_bot.

Yep i noticed, is just a matter of having both available at the same time

> Repeat this bug, but currently can't find a root of problem. Perhaps, this can't be solved without changes in text-generator-webui. Seems, this bug happend even in api mode.

Or maybe catching the exception as it appears? Just wondering

**Comment by innightwolfsleep** [comment]
Late answer, but this info should be saved in history.
Telegram_bot wont work with silero or sd api extension integrated in oobabooga because bot needs only text answers. Thats why there is separated tlelegram_bot equivalent of those extension.
