### ISSUE TITLE
Telegram Bot Extension Causes Frequent Crashes in Text Generation Web UI

### ISSUE THREAD

**Issue by barrymac** [innightwolfsleep/text-generation-webui-telegram_bot#113]
Description:

I've been encountering an inconsistent issue with the Telegram Bot extension, where it seems to crash the Text Generation Web UI nearly every time it's loaded. This has been a major hindrance to our workflow and I wanted to bring it to your attention.

Steps to Reproduce:

Launch the Text Generation Web UI.
Load the Telegram Bot extension via the UI because the command line flag is ignored 

Expected Behavior:
The Telegram Bot extension should load and be shown loaded in the logs 
`2023-08-12 18:10:23 INFO:Loading the extension "telegram_bot"...
Telegram bot generator script:  GeneratorTextGeneratorWebui
Telegram bot started! <telegram.ext.updater.Updater object at 0x7f885012a5c0>
Running on local URL:  http://0.0.0.0:7860

To create a public link, set `share=True` in `launch()`.
`

Actual Behavior:
Almost immediately upon loading the Telegram Bot extension, the Text Generation Web UI crashes, and no log output is generated, it's just frozen , and browser page shows site unavailable

Additional Information:

Browser: [e.g., Chrome 92.0, Firefox 89.0]
OS: Ubuntu cloud, Ubuntu Desktop
Error Messages: non
Telegram Bot Extension Version: many versions from 3 months ago to present

I've tried troubleshooting by starting with models loaded, or unloaded, and doesn't seem to make any difference. 

Any assistance or insights into this issue would be greatly appreciated. Thank you for your time and dedication to this project.

**Comment by innightwolfsleep** [comment]
Just reinstalled last GeneratorTextGeneratorWebui and telegram_bot. Can't repeat this bug on windows system - webui and bot works simultaneously.

p.s. but I found another bug with generation and added another one param to generation params. Perhaps it fix your bug too.

p.p.s. you can try to switch in `telegram_config.json` option  `"generator_script": "GeneratorTextGeneratorWebuiApi"` and run GeneratorTextGeneratorWebui with --api option. This can help too.

**Comment by barrymac** [comment]
Thanks very much for the reply.  

As it turns out, setting `export OOBABOOGA_FLAGS="--chat --listen  --extensions telegram_bot"`   makes it load at startup and I don't get any crashes. It only happens when I try to load it after starting.  

thanks for the tip about the api method!
