### ISSUE TITLE
generated audio from elevenlabs_tts plugin is not played

### ISSUE THREAD

**Issue by fwiessner** [innightwolfsleep/text-generation-webui-telegram_bot#118]
bot does not transmit generated audio from elevenlabs_tts plugin

**Comment by innightwolfsleep** [comment]
There is problem with reuse plugins in telegram_bot because of design... I will consider howw to integrate it in [TelegramBotSilero.py](https://github.com/innightwolfsleep/text-generation-webui-telegram_bot/blob/main/TelegramBotSilero.py).

**Comment by innightwolfsleep** [comment]
Late answer, but this info should be saved in history.
Telegram_bot wont work with silero or sd api extension integrated in oobabooga because bot needs only text answers. Thats why there is separated tlelegram_bot equivalent of those extension.
