### ISSUE TITLE
Exception on sending any message

### ISSUE THREAD

**Issue by Avanatiker** [innightwolfsleep/text-generation-webui-telegram_bot#119]
I tried with multiple oobabooga commits with any configuration and i always get this exception once i sent a message in telegram to the bot
```
user_text hi
generate_answer 'NoneType' object has no attribute 'encode'
cannot unpack non-iterable NoneType object
Exception in thread Thread-5 (thread_get_message):
Traceback (most recent call last):
  File "/home/-/Git/oobabooga_linux/installer_files/env/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/home/-/Git/oobabooga_linux/installer_files/env/lib/python3.10/threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "/home/-/Git/oobabooga_linux/text-generation-webui/extensions/telegram_bot/TelegramBotWrapper.py", line 765, in thread_get_message
    raise e
  File "/home/-/Git/oobabooga_linux/text-generation-webui/extensions/telegram_bot/TelegramBotWrapper.py", line 746, in thread_get_message
    answer, system_message = self.generate_answer(
TypeError: cannot unpack non-iterable NoneType object

**Comment by innightwolfsleep** [comment]
Just updated oobabooga via shell script, but bot still work. 
Will do clear reinstall when got fast internet connection) 


p.s. try to change in telegram_config.json:
"generator_script": "GeneratorTextGeneratorWebuiApi"
and run oobabooga  with --api.
This force telegram_bot interact with oobabooga via API, perhaps will help.

let me know if api mode help)

**Comment by innightwolfsleep** [comment]
I just made clear install of oobaboba and telegram_bot but I can't repeat your bug. 

I am using llama7b4bit model and flags:
"--chat --gpu-memory 6 --cpu-memory 6 --model llama7b4bit --sdp-attention --api --extensions telegram_bot"

Can you share details about you command flags and config? I see you are not alone with this bug https://github.com/innightwolfsleep/text-generation-webui-telegram_bot/issues/121

**Comment by Avanatiker** [comment]
Hey thanks for your response but like one day later it suddenly worked again. I noticed though that this error also comes up as soon as you text the bot without having a model loaded. (I had a model loaded when i had this issue though) still thank you for your effort in helping me!
