### ISSUE TITLE
instruct and chat-instruct mode

### ISSUE THREAD

**Issue by sakhavhyand** [innightwolfsleep/text-generation-webui-telegram_bot#120]
Hi, first i want to tell that your work is incredible.

Do you plan to add the instruct and chat-instruct mode ?
A model I use doesn't work very well in chat mode.

I planned to take a look at it myself but i'm still a beginner in python and LLM so if you have some directions to give, I will take them with pleasure.

**Comment by innightwolfsleep** [comment]
There is somethins like instruct mode - notebook and query modes. But it isтэе convenient to use to use due to telegram format, I think. Try it.
(also, you need to made a custom character file to satisfy your expectations)
