### ISSUE TITLE
Need Help on Understanding how this works  

### ISSUE THREAD

**Issue by Maki9009** [innightwolfsleep/text-generation-webui-telegram_bot#132]
Could you guide me on how to remove the character name from each message? I’m unsure about the changes needed in the configuration or rules. Also, I’ve noticed that the bot generates a context conversation in the command line that doesn’t reflect our actual conversation and isn’t relayed to the Telegram bot. I’m finding this confusing.

I’m aiming for a realistic chat experience without any additional features like buttons. Could you advise me on the settings I need to adjust to achieve this?

Lastly, does the system function correctly when LoRas are loaded in?

**Comment by innightwolfsleep** [comment]
Could you guide me on how to remove the character name from each message? I’m unsure about the changes needed in the configuration or rules. 
- this is hardcoded behaviour. You can try to change this in inside [TelegramBotWrapper.py](https://github.com/innightwolfsleep/text-generation-webui-telegram_bot/blob/main/TelegramBotWrapper.py), but I am not sure this will work properly.

Lastly, does the system function correctly when LoRas are loaded in?
- I havent tested it. This shold working in api generator mode, I think.

**Comment by innightwolfsleep** [comment]
I’m aiming for a realistic chat experience without any additional features like buttons. Could you advise me on the settings I need to adjust to achieve this?

This looks like something you want... Chat. Buttons hidden. Conversation like with human. But "Bot:" still shown
Also, curently there is no way to switch off prefixes (++, +, -- e.t.c.) 

![image](https://github.com/innightwolfsleep/text-generation-webui-telegram_bot/assets/20921671/df19ee7e-5058-441e-9274-ec33f33faecd)
[configs.zip](https://github.com/innightwolfsleep/text-generation-webui-telegram_bot/files/12597410/configs.zip)

**Comment by innightwolfsleep** [comment]
upd. 
Correct telegram_config file, previous is for llm_telegram_pot repo. Repos similiar, but have little differencies. 
[telegram_config.zip](https://github.com/innightwolfsleep/text-generation-webui-telegram_bot/files/12597490/telegram_config.zip)

**Comment by Maki9009** [comment]
i updated my Config to make it similar to what you sent here but it still has the button. and still for some reason once i text the a.i it generates a context.. and some of the replies are empty like on the CMD it would write, generation error: custom_token_bans.. and on telegram the bot just writes the "characters name : "
its empty ?

**Comment by innightwolfsleep** [comment]
Change in telegram_user_rules.json all true to flase excepr last line (except message). If this wont help - idk how to help.

generation error: custom_token_bans - interaction problem between textgenerator and code. Perhaps, this using api generator type can fix this problem. p.s. seems splved #138 by clean instal
