### ISSUE TITLE
generation error: 'custom_token_bans'

### ISSUE THREAD

**Issue by sibawal** [innightwolfsleep/text-generation-webui-telegram_bot#138]
Hello everyone, the bot stopped working. It gives a simple message and an error generation error: 'custom_token_bans'

![1](https://github.com/innightwolfsleep/text-generation-webui-telegram_bot/assets/52999882/28c27ff8-6ab2-4b0c-9295-5060e87394a8)
![image](https://github.com/innightwolfsleep/text-generation-webui-telegram_bot/assets/52999882/aa11b638-1030-42db-9ee0-3347138d7e5e)

**Comment by Maki9009** [comment]
Yeah getting the same problem

**Comment by sibawal** [comment]
> Yeah getting the same problem

Three hours ago they were still working.

**Comment by innightwolfsleep** [comment]
#139 Should be fixed now.

**Comment by sibawal** [comment]
> #139 Должно быть исправлено сейчас.

I checked, updated, still the error.

**Comment by innightwolfsleep** [comment]
Just reinstall textgenerator and telegram bot. 
Can't repeat this bug. I am using llama-2-7B, gptq and gguf modes - both work fine.

Which model/extension config/settings do you use?

**Comment by sibawal** [comment]
> Just reinstall textgenerator and telegram bot. Can't repeat this bug. I am using llama-2-7B, gptq and gguf modes - both work fine.
> 
> Which model/extension config/settings do you use?

Yes, I already did it, installed a clean Tgwebui and the Telegram bot plugin.  The same situation, the problem appeared after updating webui, otherwise I did not change anything.  The Gpt and Opt and LLaMA models show this error.

**Comment by sibawal** [comment]
Да, я уже это сделал, установил чисто Tgwebui и подключил Telegram-бота. Та же ситуация, проблема появилась после обновления вебуи, в остальном я ничего не менял. Модели Gpt, Opt и LLaMA отображают эту ошибку.

**Comment by sibawal** [comment]
The problem is solved. I reinstalled a clean text generator (after installation, do not run the update, otherwise this error will occur.) and read the installation of the telegram bot.  When installing the plugin and entering the pip install -r command text-generation-webui\extensions\telegram_bot\requirements_ext.txt an error will appear updating the googleauth version if you do not update the text generator, you just need to enter the command again and everything will be OK.
