### ISSUE TITLE
SD Images not working

### ISSUE THREAD

**Issue by iChristGit** [innightwolfsleep/text-generation-webui-telegram_bot#167]
I have Auto1111 enabled with --api and can generate through ooga
when using the telegram bot using the emoji prefix or "send an image of X"
I get this error:
Output generated in 0.76 seconds (23.68 tokens/s, 18 tokens, context 1478, seed 1466696946)
 A fast food restaurant chain famous for its burgers, fries, and other menu items
2023-11-05 12:26:58 ERROR:send_sd_image: 'images'

What am i doing wrong?

**Comment by innightwolfsleep** [comment]
Just reinstalled Auto1111 and checked - works fine.

Plz check http://127.0.0.1:7860/docs - is there  "POST txt2img_post" method?

If you running sd api with ooba api or in share mode e.t.c. sd_api URL may be changed and should be set with config.json
Also, there was a bug with automatic instalation A1111 with sd.webui.zip - api wasn't work properly... but I am not sure if this bug repeated.

**Comment by iChristGit** [comment]
> I've just reinstalled Auto1111 and checked - works fine.
> 
> Plz check http://127.0.0.1:7860/docs - is there "POST txt2img_post" method?
> 
> If you running sd api with ooba api or in share mode e.t.c. sd_api URL may be changed and should be set with config.json Also, there was a bug with automatic instalation A1111 with sd.webui.zip - api wasn't work properly... but I am not sure if this bug repeated.

My problem was that I ran ooba first,
Ive started automatic1111 first and then ooga, it works.
I guess its hardcoded to use 7860 for SD.
It all works now, Another quick question, can I remove the Bot Name: 
at the beggining of each message? and the buttons on the bottom?
Also would like to reduce or remove the delay of 10 seconds as I get responses instantly (125 tokens /s) , is that possible through editing a line?

**Comment by innightwolfsleep** [comment]
> Another quick question, can I remove the Bot Name:
at the beggining of each message? 

Perhaps, one of bot modes wiill help you.

> reduce or remove the delay of 10 seconds

Here [conf.py](https://github.com/innightwolfsleep/text-generation-webui-telegram_bot/blob/main/source/conf.py) you can change `flood_avoid_delay`

**Comment by innightwolfsleep** [comment]
> I guess its hardcoded to use 7860 for SD.

You can chang it in config file `"sd_api_url": "http://127.0.0.1:7860",`

**Comment by iChristGit** [comment]
> > I guess its hardcoded to use 7860 for SD.
> 
> You can chang it in config file `"sd_api_url": "http://127.0.0.1:7860",`

Thanks for the reply!
I just wish I could remove the codeblock format and font (so it looks more natural like a normal message)
And trying to do translation to hebrew, its not in the options, wondering if that could be done as google translate has HE-il option.

**Comment by innightwolfsleep** [comment]
> remove the codeblock format

In [conf.py](https://github.com/innightwolfsleep/text-generation-webui-telegram_bot/blob/main/source/conf.py) check html_tag:
![image](https://github.com/innightwolfsleep/text-generation-webui-telegram_bot/assets/20921671/afd38d5f-7085-43ea-82f2-a4a761e0f939)

> And trying to do translation to hebrew

In [conf.py](https://github.com/innightwolfsleep/text-generation-webui-telegram_bot/blob/main/source/conf.py) check 
language_dict:
![image](https://github.com/innightwolfsleep/text-generation-webui-telegram_bot/assets/20921671/a6d53a27-f7ef-48ba-87ce-87a232454623)

**Comment by iChristGit** [comment]
> > remove the codeblock format
> 
> In [conf.py](https://github.com/innightwolfsleep/text-generation-webui-telegram_bot/blob/main/source/conf.py) change html_tag: ![image](https://user-images.githubusercontent.com/20921671/281146433-afd38d5f-7085-43ea-82f2-a4a761e0f939.png)
> 
> > And trying to do translation to hebrew
> 
> In [conf.py](https://github.com/innightwolfsleep/text-generation-webui-telegram_bot/blob/main/source/conf.py) change language_dict: ![image](https://user-images.githubusercontent.com/20921671/281146634-a6d53a27-f7ef-48ba-87ce-87a232454623.png)

Thank you! how do I edit the html_tag? what do I put there?

**Comment by iChristGit** [comment]
I just did ["", ""]
It works! thanks
