### ISSUE TITLE
:Cant find user_rules_file_path: extensions\telegram_bot\configs\telegram_user_rules.json

### ISSUE THREAD

**Issue by Delcos** [innightwolfsleep/text-generation-webui-telegram_bot#170]
Unable to run in extension mode. It always ends in:
`
2023-11-11 13:09:12 ERROR:Cant find generator_params_file
2023-11-11 13:09:12 ERROR:Cant find user_rules_file_path: extensions\telegram_bot\configs\telegram_user_rules.json
`
Tried on two machines and fresh install.

**Comment by innightwolfsleep** [comment]
Just reinstaled text-generation-webui and reinstaled telegram bot... 
Find and fix a bug, related to generation parameters, but there is no bug like yours.

Seems, you have a problem with path. Perhaps, you put bot extension in wrong dir? Check where [telegram_user_rules.json](https://github.com/innightwolfsleep/text-generation-webui-telegram_bot/blob/main/configs/telegram_user_rules.json) place in your code?

**Comment by Harrisoned** [comment]
I suppose it's related to https://github.com/innightwolfsleep/text-generation-webui-telegram_bot/issues/176.

**Comment by innightwolfsleep** [comment]
added `normpath` #180
