### ISSUE TITLE
Issue with paths: FileNotFoundError

### ISSUE THREAD

**Issue by Harrisoned** [innightwolfsleep/text-generation-webui-telegram_bot#176]
Hello!

Got the following error while trying to run it on a fresh install:

`2023-11-14 13:02:04 INFO:Loading the extension "telegram_bot"...`
`2023-11-14 13:02:05 ERROR:Cant find generator_params_file`
`2023-11-14 13:02:05 ERROR:Cant find user_rules_file_path: extensions\telegram_bot\configs\telegram_user_rules.json
Exception in thread Thread-2 (run_server):
Traceback (most recent call last):
  File "/home/harrison/miniconda3/envs/llms/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/home/harrison/miniconda3/envs/llms/lib/python3.10/threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "/home/harrison/text-generation-webui/extensions/telegram_bot/script.py", line 20, in run_server
    tg_server.run_telegram_bot()
  File "/home/harrison/text-generation-webui/extensions/telegram_bot/main.py", line 97, in run_telegram_bot
    with open(token_file_name, "r", encoding="utf-8") as f:
FileNotFoundError: [Errno 2] No such file or directory: 'extensions\\telegram_bot\\configs\\telegram_token.txt'
`

System:
`OS: Pop!_OS 22.04 LTS x86_64`

I manage to fix it by replacing the `\\` in `ext_config.json` by `/`. I suppose there should be a mechanism to detect Linux installs and run it accordingly, using the same path styles as `collab_config.json`.
 
Awesome extension by the way.

**Comment by innightwolfsleep** [comment]
#179 Added normpath before file opening.

**Comment by Harrisoned** [comment]
It didn't work, sadly. `normpath` doesn't seem to have any effect on that case. I still get the exact same error.

I tried `normpath` on a separate script to test it's behavior and it doesn't change the slashes.

**Comment by innightwolfsleep** [comment]
Yeah. Path format changed to unix format. With `normpath` this works on windows and shold wor on unix too. #180
