### ISSUE TITLE
Error when generating: generation error: 'temperature_last'('temperature_last',)

### ISSUE THREAD

**Issue by Harrisoned** [innightwolfsleep/text-generation-webui-telegram_bot#177]
Got this error when trying to generate with ExLlama_HF:

`generation error: 'temperature_last'('temperature_last',)`

Tracked the issue down to https://github.com/oobabooga/text-generation-webui/pull/4472. I used an updated install.  I don't know if this happens with other modules, but i think it does judging by the PR at the application, as all modules where updated.

I fixed it by adding the parameter `temperature_last` on `source/generators/generator_text_generator_webui.py` at where it creates the parameters before sending to `generate_reply`, with a `False` value. Hope it helps.

**Comment by innightwolfsleep** [comment]
#177 added temperature_last
