### ISSUE TITLE
Responding with first line only in case of bullet points

### ISSUE THREAD

**Issue by leito711** [innightwolfsleep/text-generation-webui-telegram_bot#196]
I have asked how to make lasagna recipe but in all scenarios it only reponds with the first line of the message. If I ask to respond in a long single sentence without bullet points then a longer response is displayed.
![image](https://github.com/innightwolfsleep/text-generation-webui-telegram_bot/assets/156906212/eac03a74-333f-4097-a44b-6944315d0a39)

**Comment by innightwolfsleep** [comment]
Remove "\n" from stopping_strings list in [generator_params.json](https://github.com/innightwolfsleep/text-generation-webui-telegram_bot/blob/main/configs/generator_params.json)

("\n" was added to avoid too large ansvers in some models, but this is not necessary stopping option)
