### ISSUE TITLE
Bot is broken since today

### ISSUE THREAD

**Issue by mustang651** [innightwolfsleep/text-generation-webui-telegram_bot#203]
The bot has been broken since today. No updates, no config changes, no errors in the webui console. It just shows initial context messages and that's all

**Comment by innightwolfsleep** [comment]
#204 change openapi code. Check it please. Hae to bo work properly now.

**Comment by mustang651** [comment]
no, still the same. how can help you with this?

**Comment by innightwolfsleep** [comment]
Share your cmd flags.

**Comment by mustang651** [comment]
--api --extensions code_syntax_highlight telegram_bot webui_tavernai_charas
and just in case
![image](https://github.com/innightwolfsleep/text-generation-webui-telegram_bot/assets/19196847/715254d1-edc3-44ad-964d-3633a8b9cb59)

**Comment by innightwolfsleep** [comment]
#205 It was pretty foolish mistake... Fixed. Now shold working. (Works fine at mine laptop)

**Comment by innightwolfsleep** [comment]
#206 fixed. Works fine on my PC.

**Comment by mustang651** [comment]
thanks
