### ISSUE TITLE
Error Extension Mode: Connection Refused

### ISSUE THREAD

**Issue by SleepyRizi** [innightwolfsleep/text-generation-webui-telegram_bot#209]
**Description**

I encountered a connection error when using the extension mode. The error occurs when attempting to receive text through telegram, post-model load and UI restart.

![image](https://github.com/innightwolfsleep/text-generation-webui-telegram_bot/assets/46001327/fb6a49a1-7948-4842-a2ed-7e08d1f881e6)

**Settings:**
![Capture](https://github.com/innightwolfsleep/text-generation-webui-telegram_bot/assets/46001327/3f168c4e-ab82-4dbd-ba39-abd2abfeb354)

**Response:**
![image](https://github.com/innightwolfsleep/text-generation-webui-telegram_bot/assets/46001327/f714f2d2-d5e5-4863-802d-8efe13dfaf22)

**Additional Information**

    My VPN is enabled due to external internet restrictions (telegram won't work otherwise).

**Comment by innightwolfsleep** [comment]
Seems, there is problem in api.
Check if http://127.0.0.1:5000/docs available.

**Comment by SleepyRizi** [comment]
nope, Unable to connect.

**Comment by SleepyRizi** [comment]
aIso I checked:
curl http://127.0.0.1:5000/v1/completions
curl: (7) Failed to connect to 127.0.0.1 port 5000 after 2046 ms: Couldn't connect to server

**Comment by innightwolfsleep** [comment]
I see your flag set right. API should be available. This is an https://github.com/oobabooga/text-generation-webui bug. Try to open issue about api availability.

p.s. try http://<YOUR_PUBLIC_IP>:5000/docs available. Perhaps it because of your system.
