### ISSUE TITLE
Prompt loses character summary when enough message history pushes it out

### ISSUE THREAD

**Issue by uncreativedan** [innightwolfsleep/text-generation-webui-telegram_bot#26]
It seems a downside to storing the character summary/traits/etc in the same json as the message history and then sending that whole file to the prompt means that when you send enough messages, the token limit will soon push the character summary out of the prompt rather than keeping it at the top. 

I noticed my character suddenly lost memory of all their traits while chatting and checking the text-generation-webui console showed their traits had indeed been truncated.

**Comment by innightwolfsleep** [comment]
Added smart history truncating. Context never erased. 
First erased message examples
Then erased greetings
In the end - erased oldest chat history.
