### ISSUE TITLE
New Issue KeyError : 'stream'

### ISSUE THREAD

**Issue by TruthSearchers** [innightwolfsleep/text-generation-webui-telegram_bot#31]
Hey man , how are you 
Look like oobaboooga update custom generation function they added stream 
Causing this problem

**Comment by TruthSearchers** [comment]
still facing this issue

**Comment by innightwolfsleep** [comment]
Added "stream" in generation params. Should fix a problem.

**Comment by TruthSearchers** [comment]
Yup it's fixed thanks bro
