### ISSUE TITLE
KeyError: 'stream'

### ISSUE THREAD

**Issue by SuperMaoUwU** [innightwolfsleep/text-generation-webui-telegram_bot#32]
After oobabooga reinstall it does not work on the new ooba version resulting on: Traceback (most recent call last):
  File "C:\Users\woda9\Downloads\newinstall\text-generation-webui\modules\text_generation.py", line 286, in generate_reply_custom
    if not state['stream']:
KeyError: 'stream'
generate_answer local variable 'output' referenced before assignment

**Comment by innightwolfsleep** [comment]
Did you tried update telegram bot? This error should be already fixed.
