### ISSUE TITLE
Which text-generation-webui commit is this extension compatible with?

### ISSUE THREAD

**Issue by MichaelDoron** [innightwolfsleep/text-generation-webui-telegram_bot#40]
I noticed that a few aspects of the newer text-generation-webui code are no longer compatible with this extension
(e.g., like `get_available_models` is now part of `utils` and not `server`)

Which commit is the extension based on?

Thanks!

**Comment by innightwolfsleep** [comment]
Cant say diffenetly now, but it was added 21 april. 
I will check compatible with new version later.

**Comment by innightwolfsleep** [comment]
Fixed.
