### ISSUE TITLE
epsilon_cutoff

### ISSUE THREAD

**Issue by c4m3r0nn** [innightwolfsleep/text-generation-webui-telegram_bot#41]
I am using the Telegram bot with the Oobabooga Google Colab. 

I am able to connect however every message is empty and the terminal says generate_answer ‘epsilon_cutoff’

any ideas on a fix for this?

**Comment by stfzz** [comment]
Same for me using ookabooga locally. I connect to telegram, can see the bot, chose characters etc, but no answer is generated, All I see in terminal is "generate_answer 'mirostat_mode'" everytime an answer should be generated. Tried everything but Am not able to solve the issue.

**Comment by innightwolfsleep** [comment]
I just aligned text generator in https://github.com/innightwolfsleep/text-generation-webui-telegram_bot/pull/42 to oobabooga 
new version. But I cant check it now. If one of you can check changes - please write here result.

**Comment by c4m3r0nn** [comment]
Can confirm working for me now :) thank you for helping and making this git

**Comment by stfzz** [comment]
Sorry, not working for me. Still getting the "generate_answer 'mirostat_mode'" in terminal and nothing in telegrm

**Comment by stfzz** [comment]
Also, I wonder why I get the "generate_answer 'mirostat_mode'" only for the Telegram extension and not when using the model through ookabooga UI.

**Comment by stfzz** [comment]
Not really. No more "generate_answer 'mirostat_mode'" and an answer is displayed in telegram. But it's a long repeating of my prompt and empty answer from bot, like:
You: Hi
Bot:
You: hi
Bot:
You: hi
Bot
...and so on

**Comment by stfzz** [comment]
I'll do some tests and keep you posted. Thanks for your efforts.

**Comment by Bahamut-ru** [comment]
@stfzz do you update the extension? I'm run cmd_windows.bat
```
cd text-generation-webui
cd extensions
cd telegram_bot
git pull
```
and all worked for me: ggml v3 8bit 13B, gptq 7B, 13B

**Comment by stfzz** [comment]
Maybe someone can share the used settings for the telegram extension and ookabooga itself?

**Comment by stfzz** [comment]
My guess is it is an eos_token issue. Trying to solve it...

**Comment by stfzz** [comment]
Thanks.
I was trying to use telegram_config.cfg for this. Will try modifying code.

**Comment by innightwolfsleep** [comment]
+ to my todo list: move stopping_strings and eos_token to telegram_config.cfg ))))))

**Comment by stfzz** [comment]
Would that look like this: 

stopping_strings.append(r"\nYou:")

?

**Comment by innightwolfsleep** [comment]
I am realy dont know what exactly wrong. 
I use ordinary settings - llama-7b-4bit and "NovelAI-Sphinx Moth" preset and it work fine. 
Vicuna have specific syntax and thats may be reason why it work not properly. If bot send empty answer - this means problem happend when it send "question" to text-generation-webui generate_reply function and it cant answer. When i got similiar problem, i try to debug what generate_reply do. I cant get same result as you so i cant help. If you can share link to your model i can try to repeat.

**Comment by stfzz** [comment]
Hi. Thanks for pointing out some directions. Will investigate further.
I was using "ggml-vic7b-uncensored-q5_1" from this repo: https://huggingface.co/eachadea/ggml-vicuna-7b-1.1/tree/main

**Comment by TruthSearchers** [comment]
I am using 65B model it working absolutely fine without problem 
Some models need specific stopping strings

**Comment by stfzz** [comment]
Is this the right way to add stopping strings to TelegramBotGenerator.py:

stopping_strings.append(r"\nHuman:")

**Comment by innightwolfsleep** [comment]
> Is this the right way to add stopping strings to TelegramBotGenerator.py?
> stopping_strings.append(r"\nHuman:")
Right.

If wont work - try 
  stopping_strings.append("Human:")

**Comment by stfzz** [comment]
Already tried :-)

**Comment by innightwolfsleep** [comment]
I made custom character and got result
[Answerer_vic7b.zip](https://github.com/innightwolfsleep/text-generation-webui-telegram_bot/files/11578728/Answerer_vic7b.zip)

![2](https://github.com/innightwolfsleep/text-generation-webui-telegram_bot/assets/20921671/a438a09c-d3bf-4a09-9fdc-eb9e5509428f)

**Comment by stfzz** [comment]
Back to generating text, pretty good indeed. Just can't figure out how to male it stop chat with itself

**Comment by innightwolfsleep** [comment]
> to my todo list: move stopping_strings and eos_token to telegram_config.cfg ))))))

Added.

**Comment by stfzz** [comment]
Thanks a lot for your help! Managed to make it work, also thanks to your suggestions.
