### ISSUE TITLE
import error

### ISSUE THREAD

**Issue by johnnybeatzxxd** [innightwolfsleep/text-generation-webui-telegram_bot#46]
![photo_2023-05-27_02-42-03](https://github.com/innightwolfsleep/text-generation-webui-telegram_bot/assets/120090400/9be9e3aa-e2c9-4ee4-8115-7f401a2d47cc)
it looks like i cloned it in the wrong directory can you help me out?

**Comment by innightwolfsleep** [comment]
It is clones right to right place. Which error you got?

Perhaps you need do "pip install -r extensions\telegram_bot\requirements.txt"

**Comment by johnnybeatzxxd** [comment]
> It is cloned to right place. Perhaps you need do "pip install -r extensions\telegram_bot\requirements.txt"

i did
![image](https://github.com/innightwolfsleep/text-generation-webui-telegram_bot/assets/120090400/2b49de44-7d69-42fe-a7ff-72fae397ec6c)

**Comment by innightwolfsleep** [comment]
You dont need run script.py directly, you need to run webui.py (or server.py) to run whole https://github.com/oobabooga/text-generation-webui with https://github.com/innightwolfsleep/text-generation-webui-telegram_bot as extension. 

text-generation-webui-telegram_bot is extension for text-generation-webui, not standalone script.

**Comment by innightwolfsleep** [comment]
Go to [oobabooga/text-generation-webui](https://github.com/oobabooga/text-generation-webui) and install.  There are instruction how to install, download model and to start using. 
When you will got a properly webui from [oobabooga/text-generation-webui](https://github.com/oobabooga/text-generation-webui) - clone telegram_bot to extension folder. 
Then set telegram api in telegram_token.txt. 
Then run [oobabooga/text-generation-webui](https://github.com/oobabooga/text-generation-webui) with "--extensions telegram_bot" (there are explaining how to run extension)
Thats all.

**Comment by johnnybeatzxxd** [comment]
thank you so much its working completely fine
