### ISSUE TITLE
Fails to send messages to the model. "generate_answer 'tfs'"

### ISSUE THREAD

**Issue by Redenrik** [innightwolfsleep/text-generation-webui-telegram_bot#50]
today for no apparent reasons the telegram-bot stopped working, each time i try to send it a message it simply answer me with only the character name and nothing inside the message, on the text-generatio terminal window it prints:

generate_answer 'tfs'

each time I try to send a message.

**Comment by innightwolfsleep** [comment]
Append to default param 'tfs': 1.0 and 'top_a': 0.0. Check it, plz.

**Comment by Gustavsenay** [comment]
Unfortunally it still don't work, I'll try to reinstall and let you know

**Comment by Redenrik** [comment]
I confirmu that after deleting and reinstall of the extension it works! Thank you @innightwolfsleep !

**Comment by Redenrik** [comment]
It don't print anymore "generate_answer 'tfs'" but now the chat in telegram don't generate anything but sometimes prints </s>

**Comment by innightwolfsleep** [comment]
Hm... I am reinstaled ooba today to code new feature... and my last commit (just few minutes ago) works fine with it (llama 7b 4bit model). 
Can you check? If it work fine - share details please.
