### ISSUE TITLE
Unexpected Keyword argument

### ISSUE THREAD

**Issue by ric3b0wl** [innightwolfsleep/text-generation-webui-telegram_bot#66]
Hi
I got 
```
generate_answer _generate_reply() got an unexpected keyword argument 'eos_token'
```
Every time I send any response via telegram bot. Any idea?
Thanks

**Comment by innightwolfsleep** [comment]
Try again. Align to new text generator version.

**Comment by vishusinghal** [comment]
getting the following error now

generate_answer 'repetition_penalty_range'

any ideas why?

**Comment by innightwolfsleep** [comment]
Okay... i've just updated my ooba version and fix generator. Now it works for me. Should be fine now.

**Comment by vishusinghal** [comment]
yes, its fixed now
