### ISSUE TITLE
It seems that bot is broken on the current version of text-generation-webui

### ISSUE THREAD

**Issue by goodglitch** [innightwolfsleep/text-generation-webui-telegram_bot#74]
Hi! 

First of all let me say that this is fantastic work. I am writing my own telegram bot, but yours seems to be miles ahead. Unfortunately, I was not able to try it out. When I run it on telegram it seems to connect properly to API as it sees all downloaded models, but I can't get it to reply me to any message. So after /start whatever I write there is no reply. Can you please check that it still works on the current version of text-generation-webui. I do not see any error messages in the text-generation-webui console. Just in case here are extensions that are loaded: 
![image](https://github.com/innightwolfsleep/text-generation-webui-telegram_bot/assets/49197548/b1a4201f-b5de-44d5-b2d8-c950dc30d132)

I am using openai for my own bot.

**Comment by goodglitch** [comment]
Strange enough, it replies if I start phrase with slash. Like /hi. I thought these are reserved for commands. If it is intended behavior please update readme.md and close the issue.

**Comment by innightwolfsleep** [comment]
No, this is unexpected behavior. I just made clear updated text-generation-webui and check the same extension config with llama7b4bit... It works fine. 

I cant repeat your problem. Perhaps, I need some load extensions in difenetly sequence to repeat...

P.s. Also I updated behaviour of telegram_bot with "character" Vicuna-v1.1.yaml. Perhaps, this can help, but this is not a reason of your problem.

P.p.s. telegram_bot shouldn't interact with api or open_ai extensions - telegram_bot call generate method from text-generation-webui directly.

**Comment by goodglitch** [comment]
Thanks for the reply! 
![image](https://github.com/innightwolfsleep/text-generation-webui-telegram_bot/assets/49197548/be9f0125-e391-4298-b155-65d37af50fcf)

That is what I am talking about. Last time I updated text-generation-webui was like 2 or 3 days ago. I prefer not to update it very frequently as some updates have tendency to break everything down.

**Comment by innightwolfsleep** [comment]
Is there any errors in text-generation-webui console window?

**Comment by goodglitch** [comment]
As far as I can see no. The error that you can see here occurred much later at 21:01 and I believe is related to the internet connection.

![image](https://github.com/innightwolfsleep/text-generation-webui-telegram_bot/assets/49197548/dd8c078f-b531-466c-86f2-132db15c7b31)

**Comment by ManuXD32** [comment]
I have the exact same problem but I only load the telegram_bot extension

**Comment by ManuXD32** [comment]
After changing some setting a realised that the problem might be with the example.yaml character, try another one and It should work

**Comment by innightwolfsleep** [comment]
If 

> Thanks for the reply! ![image](https://user-images.githubusercontent.com/49197548/253635559-be9f0125-e391-4298-b155-65d37af50fcf.png)
> 
> That is what I am talking about. Last time I updated text-generation-webui was like 2 or 3 days ago. I prefer not to update it very frequently as some updates have tendency to break down everything and I have friends who are using my bot.

Seems problem with ignoring of messages without "/" is result of group bot policy. You can change it with bot_father.
