### ISSUE TITLE
Set to anything other than admin mode?

### ISSUE THREAD

**Issue by Delcos** [innightwolfsleep/text-generation-webui-telegram_bot#87]
Can it be changed to something else, I tried to add user instead and it says it's invalid.

**Comment by innightwolfsleep** [comment]
What exactly do you mean?

Default admin mode may be changed by setting bot_mode=admin  in [telegram_config.cfg](https://github.com/innightwolfsleep/text-generation-webui-telegram_bot/blob/main/telegram_config.cfg)
There is 6 modes
    MODE_ADMIN = "admin"
    MODE_CHAT = "chat"
    MODE_CHAT_R = "chat-restricted"
    MODE_NOTEBOOK = "notebook"
    MODE_PERSONA = "persona"
    MODE_QUERY = "query"

**Comment by innightwolfsleep** [comment]
Do you add user as nickname or id? (You should use id, ask @getmyid_bot to get it)
