### ISSUE TITLE
Does admin.txt work?

### ISSUE THREAD

**Issue by xshinoryu** [innightwolfsleep/text-generation-webui-telegram_bot#91]
So I've read the recent readme, and added myself (my telegram ID) in there, then launched the bot in persona  mode so that other people could not change anything. 
However, when I try to change something, it still does not let me to, it thinks I am a basic user and does not add anything to settings

**Comment by innightwolfsleep** [comment]
Thats because currently bot see no difference between chat id and user id. Chat - is like single user, regardless who exactly write message. 
Will be changed in future.

**Comment by xshinoryu** [comment]
Thanks! Looking forward to that! (tho I tried using it not in a group chat  and I still can't change anything, even though my id is in the admin list (runnng the bot in persona mode))

**Comment by innightwolfsleep** [comment]
UPD.
Just fixed bug with admin list - now it works in private chat properly.

**Comment by xshinoryu** [comment]
Great!
