### ISSUE TITLE
Extension isn't picking up the config file

### ISSUE THREAD

**Issue by krypterro** [innightwolfsleep/text-generation-webui-telegram_bot#93]
I'm getting the default character and mode, and the Telegram bot loads the Chiharu Yamada character every time, and I'm not exactly sure from where, as I only have one character. 

Should I have to do anything extra to make the extension use the data from telegram_config.cfg?

**Comment by innightwolfsleep** [comment]
Chiharu Yamada - is Example.yaml from character, loaded by default both to webui and telegram_bot.
If you 
Try to shoutdown bot, clear bot history directory, run bot again.  Or just press reset button, this may help too.

telegram_config.cfg should be enough. Share config if history clearing wont help.

**Comment by krypterro** [comment]
I restarted the bot several times and deleted the Example.yaml, finally deleted the history files from the extension, and it appears to be using our character now, but although we have it set to persona we are still getting Next and Option buttons. Is there a mode with no buttons?

**Comment by innightwolfsleep** [comment]
> Is there a mode with no buttons?
No.
But you can change user_rules dict in [TelegramBotWrapper.py](https://github.com/innightwolfsleep/text-generation-webui-telegram_bot/blob/main/TelegramBotWrapper.py)
All BTN_* for MODE_PERSONA to 0.

**Comment by krypterro** [comment]
Got it, that wirks, thanks. Awesome extension BTW, very useful for those of us the live in Telegram.
